# Generated by Django 5.2.6 on 2025-09-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id_ingredient', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_ingredient', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=50)),
                ('adresse_electronique', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id_recette', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_categorie', models.ForeignKey(blank=True, db_column='id_categorie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.categorie')),
                ('id_utilisateur', models.ForeignKey(blank=True, db_column='id_utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.utilisateur')),
            ],
            options={
                'db_table': 'recette',
            },
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id_etape', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_etape', models.BigIntegerField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('id_recette', models.ForeignKey(blank=True, db_column='id_recette', null=True, on_delete=django.db.models.deletion.CASCADE, to='recettes.recette')),
            ],
            options={
                'db_table': 'etape',
                'ordering': ['id_recette', 'numero_etape'],
            },
        ),
        migrations.CreateModel(
            name='RecetteIngredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ingredient', models.ForeignKey(db_column='id_ingredient', on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient')),
                ('id_recette', models.ForeignKey(db_column='id_recette', on_delete=django.db.models.deletion.CASCADE, to='recettes.recette')),
            ],
            options={
                'db_table': 'recette_ingredient',
                'unique_together': {('id_recette', 'id_ingredient')},
            },
        ),
    ]
