# Generated by Django 5.2.6 on 2025-09-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='etape',
            options={'managed': False, 'ordering': ['id_recette', 'numero_etape']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recette',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recetteingredient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
    ]
